### ISSUE TITLE
Write a README.md for task-0-data preparation process

### ISSUE THREAD

**Issue by ahmedtarek26** [OmdenaAI/egypt-roommate-compatibility#1]
Write a README.md file that contains task-0-data preparation details in this path :
https://github.com/OmdenaAI/egypt-roommate-compatibility/tree/main/src/tasks/task-0-data-collection

Include the process, results for your research, and the result after the discussion
provide resource links

**Comment by Akash190104** [comment]
@ahmedtarek26 I have written this and pushed it. Please check and merge #2 if there are no issues.
